# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Set managed_platform
  ansible.builtin.set_fact:
    managed_platform: "{{ 'api.mpp' in host }}"
  tags:
    - always

- name: Set with_sandbox
  ansible.builtin.set_fact:
    with_sandbox: "{{ service == 'packit' }}"
  tags:
    - always

- name: Set sandbox_namespace
  when: with_sandbox
  tags:
    - always
  block:
    - name: Set sandbox_namespace (MP+)
      ansible.builtin.set_fact:
        sandbox_namespace: "{{ tenant }}--{{ deployment }}-sandbox"
      when: managed_platform
    - name: Set sandbox_namespace
      ansible.builtin.set_fact:
        sandbox_namespace: "{{ service }}-{{ deployment }}-sandbox"
      when: not managed_platform

- name: Set redis hostname
  tags:
    - always
  block:
    - name: Set redict as the redis hostname
      ansible.builtin.set_fact:
        redis_hostname: redict
      when: with_redict

    - name: Set redis as the redis hostname (backward compatibility)
      ansible.builtin.set_fact:
        redis_hostname: redis
      when: with_redis

    - name: Warn if neither is set
      ansible.builtin.assert:
        that: with_redict or with_redis
        fail_msg: "[FAIL] Neither redict or redis is set to be deployed!"
