# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Create secrets directory hierarchy
  ansible.builtin.file:
    path: "{{ path_to_secrets }}"
    state: directory
    mode: 0755
