# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Clean up a project
  hosts: all
  vars:
    service: "{{ lookup('env', 'SERVICE') | default('packit', True) }}"
    deployment: "{{ lookup('env', 'DEPLOYMENT') }}"
  tasks:
    - name: Include variables
      ansible.builtin.include_vars: ../vars/{{ service }}/{{ deployment }}.yml

    - name: Login
      ansible.builtin.command: oc login {{ host }} --token={{ api_key }} --insecure-skip-tls-verify
      # it doesn't change anything, so don't report 'changed'
      changed_when: false

    - name: Switch to project
      ansible.builtin.command: oc project {{ project }}
      # it doesn't change anything, so don't report 'changed'
      changed_when: false

    - name: Delete all
      ansible.builtin.command: oc delete all,cm,pvc --all
      when: deployment != "prod"
      # on stage this always changes something
      changed_when: true
