# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Deploy as tmt/vagrant user
  hosts: all
  become: true
  become_user: "{{ user }}"
  become_flags: -i
  vars:
    test_project_name: myproject

  roles:
    - role: deploy

  post_tasks:
    - name: Delete test project namespace if already exist
      k8s:
        name: "{{ test_project_name }}"
        api_version: v1
        kind: Namespace
        state: absent
