name: Build & push cron-job images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - cron-jobs/import-images/**

jobs:
  build-and-push:
    # To not run in forks
    if: github.repository_owner == 'packit'

    name: Build and push image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: import-images

    env:
      path: cron-jobs/${{ matrix.image }}/

    steps:
      - uses: actions/checkout@v3

      - name: Add short SHA to the list of tags
        shell: bash
        run: |
          echo "tags=latest ${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        id: calculate-tags

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ${{ env.path }}Containerfile
          image: ${{ matrix.image }}
          context: ${{ env.path }}
          oci: true
          tags: ${{ steps.calculate-tags.outputs.tags }}

      - name: Push To Quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/packit
          username: ${{ secrets.QUAY_IMAGE_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_BUILDER_TOKEN }}
