name: Schedule tests on Testing Farm
on:
  pull_request:

# The concurrency key is used to prevent multiple workflows from running at the same time
concurrency:
  group: my-concurrency-group
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Schedule tests on Testing Farm
        uses: sclorg/testing-farm-as-github-action@v2
        with:
          compose: CentOS-Stream-9
          api_key: ${{ secrets.TF_API_KEY }}
          git_url: "https://github.com/packit/deployment"
          git_ref: "tf-openshift-tests"
          tmt_plan_regex: "deployment/remote"
          tmt_hardware: '{"memory": ">= 13 GiB", "disk": [{"size": ">= 100 GB"}], "cpu": {"cores": ">= 6"}, "virtualization": {"is-supported": true}}'
          pull_request_status_name: "Deployment"
          timeout: 3600
          secrets: CRC_PULL_SECRET=${{ secrets.CRC_PULL_SECRET }}
